import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,CalendarDays,Check,ChevronLeft,ChevronRight,ClipboardList,ExternalLink,FileText,LayoutGrid,List,Plus,RefreshCw,Search,Users} from 'lucide-react';
import {uploadFile,when} from '../workflow/data';
import {getMissionBoard,getMissionContext,getMissionDetail,missionAction,missionDownload,missionError} from './mission-data';
import {canRequestJoin,createPayload,eventDescription,googleResource,localDay,missionEventNames,missionStates,personalEntries,weekDays} from './mission-model';
import './missions.css';

const emptyBoard={items:[],total:0,stats:{}};
const field=(form,setForm,key)=>({value:form[key],onChange:e=>setForm({...form,[key]:e.target.value})});
const statusName=status=>missionStates[status]||status;
const roleNames={super_admin:'سوبر أدمن',admin:'أدمن',employee:'موظف'};
const viewTitles={operations:'غرفة العمليات',mine:'عملي ومواعيدي',available:'مهام متاحة',drafts:'مسودات المهام',completed:'المهام المنجزة',overview:'الفريق يبدأ من هنا'};
const personLabel=person=>person.name&&person.name!==person.email?`${person.name}${person.job_title?` — ${person.job_title}`:''}`:`حساب ${roleNames[person.role]||'فريق'} — ${person.email||person.name}`;
function Badge({status}){return <span className={`ms-badge ms-status-${status}`}>{statusName(status)}</span>;}
function ErrorMessage({message}){return message?<div className="ms-error" role="alert">{message}</div>:null;}
function Empty({children}){return <div className="ms-empty"><ClipboardList size={28} aria-hidden="true"/><p>{children}</p></div>;}
function Button({children,primary=false,...props}){return <button type="button" className={`ms-button${primary?' ms-primary':''}`} {...props}>{children}</button>;}
function useMissionRefresh(callback,enabled=true){
 const latest=useRef(callback);latest.current=callback;
 useEffect(()=>{if(!enabled)return;let active=true;const refresh=()=>{if(active&&document.visibilityState==='visible')Promise.resolve(latest.current()).catch(()=>{});};const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return ()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[enabled]);
}
const blankForm=()=>({title:'',description:'',drive_url:'',map_url:'',execution_at:'',departments:[]});
const dateInput=value=>{if(!value)return '';const d=new Date(value);return `${localDay(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
const draftForm=detail=>detail?{title:detail.mission.title,description:detail.mission.description,drive_url:detail.mission.drive_url||'',map_url:detail.mission.map_url||'',execution_at:dateInput(detail.mission.execution_at),departments:detail.departments.map(d=>({service_id:d.service_id,requirements:d.requirements,execution_at:dateInput(d.execution_at),due_at:dateInput(d.due_at)}))}:blankForm();
const fileAccept='image/jpeg,image/png,image/webp,image/gif,image/heic,video/mp4,video/webm,video/quicktime,application/pdf,text/plain,application/zip,.doc,.docx,.xls,.xlsx,.ppt,.pptx';
function FileInput({files,setFiles,disabled=false,existing=0}){return <label className="ms-field ms-file-field"><span>مرفقات المهمة</span><input type="file" multiple accept={fileAccept} disabled={disabled} onChange={e=>setFiles([...e.target.files])}/><small>صور وفيديو وPDF وملفات Office وZIP وملفات نصية حتى 100 ميجابايت للملف و20 مرفقا للمهمة</small>{files.length>0&&<span className="ms-selected-files">{files.map(f=>f.name).join(' · ')}</span>}{files.length+existing>20&&<span role="alert">الحد الأقصى 20 مرفقا</span>}</label>;}
async function attachFiles(mission,files,setProgress,existing=0){
 if(!files.length)return mission;
 if(files.length>20)throw Object.assign(new Error('يمكن إضافة 20 مرفقا كحد أقصى'),{userFacing:true});
 if(files.some(f=>f.size>100*1024*1024))throw Object.assign(new Error('حجم كل مرفق يجب ألا يتجاوز 100 ميجابايت'),{userFacing:true});
 const uploaded=[];
 for(const [index,file] of files.entries()){setProgress(`رفع ${index+1} من ${files.length} — ${file.name}`);uploaded.push(await uploadFile(mission.id,'brief',file,{bucket:'mission-files'}));}
 const latest=await getMissionDetail(mission.id),registered=new Set((latest.attachments||[]).map(file=>file.object_path)),pending=uploaded.filter(file=>!registered.has(file.object_path));
 if(registered.size+pending.length>20)throw Object.assign(new Error('يمكن إضافة 20 مرفقا كحد أقصى'),{userFacing:true});
 const updated=pending.length?await missionAction('attach',{id:mission.id,version:latest.mission.version,files:pending.map(({object_path,filename})=>({object_path,filename}))}):latest.mission;
 for(const item of uploaded){try{localStorage.removeItem(item.cache_key);}catch{/* optional upload metadata */}}return updated;
}

function MissionComposer({context,onClose,onSaved,initialDetail=null}){
 const [form,setForm]=useState(()=>draftForm(initialDetail)),[files,setFiles]=useState([]),[draft,setDraft]=useState(initialDetail?.mission||null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState('');
 const submission=useRef(crypto.randomUUID()),formElement=useRef(null);
 const toggleDepartment=id=>setForm(old=>({...old,departments:old.departments.some(d=>d.service_id===id)?old.departments.filter(d=>d.service_id!==id):[...old.departments,{service_id:id,requirements:'',execution_at:old.execution_at,due_at:''}]}));
 const changeDepartment=(id,key,value)=>setForm(old=>({...old,departments:old.departments.map(d=>d.service_id===id?{...d,[key]:value}:d)}));
 async function save(publish){
  if(busy)return;setBusy(true);setError('');setProgress('حفظ بيانات المهمة');let saved=draft;
  try{const payload=createPayload(form,submission.current);if(!saved){saved=await missionAction('create',payload);}else{const {submission_key,...changes}=payload;saved=await missionAction('update_draft',{id:saved.id,version:saved.version,...changes});}setDraft(saved);saved=await attachFiles(saved,files,setProgress);setDraft(saved);setFiles([]);if(publish){setProgress('نشر المهمة وإشعار الفريق');saved=await missionAction('publish',{id:saved.id,version:saved.version});}onSaved(saved.id);}
  catch(e){setError(missionError(e));if(saved){try{const latest=await getMissionDetail(saved.id);if(latest.mission.status!=='draft'){onSaved(saved.id);return;}setDraft(latest.mission);}catch{/* retain original failure and editable draft */}}}finally{setBusy(false);setProgress('');}
 }
 return <section className="ms-compose" aria-labelledby="ms-create-heading"><div className="ms-section-head"><div><span className="ms-eyebrow">من الفكرة إلى التنفيذ</span><h2 id="ms-create-heading">{initialDetail?'تعديل مسودة المهمة':'مهمة جديدة للفريق'}</h2><p>حدد النتيجة المطلوبة والأقسام والمواعيد ثم انشر المهمة</p></div><Button onClick={onClose} disabled={busy}><ArrowRight size={17}/>عودة</Button></div>
 <form ref={formElement} onSubmit={e=>{e.preventDefault();save(true);}}><fieldset disabled={busy} className="ms-form-grid">
 <label className="ms-field ms-wide"><span>عنوان المهمة</span><input required minLength={3} maxLength={200} placeholder="مثال: إنتاج حملة إطلاق الهوية" {...field(form,setForm,'title')}/></label>
 <label className="ms-field ms-wide"><span>وصف المهمة</span><textarea required minLength={10} rows={4} maxLength={12000} placeholder="شارك الفريق الهدف والتفاصيل التي تساعدهم على التنفيذ" {...field(form,setForm,'description')}/></label>
 <label className="ms-field"><span>تاريخ تنفيذ المهمة</span><input required type="datetime-local" {...field(form,setForm,'execution_at')}/></label>
 <label className="ms-field"><span>رابط Google Drive <small>اختياري</small></span><input type="url" dir="ltr" placeholder="https://drive.google.com/…" {...field(form,setForm,'drive_url')}/></label>
 <label className="ms-field ms-wide"><span>موقع المهمة على Google Maps <small>اختياري</small></span><input type="url" dir="ltr" placeholder="https://maps.app.goo.gl/…" {...field(form,setForm,'map_url')}/></label>
 <div className="ms-wide"><h3>الأقسام المعنية</h3><p className="ms-muted">اختر من أقسام المنصة وحدد المطلوب من كل قسم</p><div className="ms-dept-choices">{context.departments.map(d=><label key={d.id}><input type="checkbox" checked={form.departments.some(x=>x.service_id===d.id)} onChange={()=>toggleDepartment(d.id)}/>{d.name}</label>)}</div>{!context.departments.length&&<p>أضف الأقسام من إدارة الأقسام قبل إنشاء مهمة</p>}</div>
 {form.departments.map((d,index)=><div className="ms-department-form ms-wide" key={d.service_id}><h3><span>{String(index+1).padStart(2,'0')}</span>{context.departments.find(x=>x.id===d.service_id)?.name}</h3><label className="ms-field"><span>المطلوب من القسم</span><textarea required minLength={3} maxLength={6000} rows={3} value={d.requirements} onChange={e=>changeDepartment(d.service_id,'requirements',e.target.value)}/></label><div className="ms-form-grid"><label className="ms-field"><span>تاريخ التنفيذ</span><input type="datetime-local" required min={form.execution_at} value={d.execution_at} onChange={e=>changeDepartment(d.service_id,'execution_at',e.target.value)}/></label><label className="ms-field"><span>آخر موعد للتسليم</span><input type="datetime-local" required min={d.execution_at} value={d.due_at} onChange={e=>changeDepartment(d.service_id,'due_at',e.target.value)}/></label></div></div>)}
 </fieldset><FileInput files={files} setFiles={setFiles} disabled={busy}/>{draft&&<p className="ms-notice">تم حفظ بيانات المهمة كمسودة يمكنك استكمال رفع المرفقات والنشر بأمان</p>}<ErrorMessage message={error}/><p role="status" className="ms-muted">{progress}</p><div className="ms-form-footer"><Button primary type="submit" disabled={busy||!context.departments.length}><Plus size={17}/>نشر المهمة</Button><Button disabled={busy} onClick={()=>{if(formElement.current?.reportValidity())save(false);}}>حفظ مسودة</Button><small>يتولى الأوبريشن توزيع الفريق ومتابعة التنفيذ</small></div></form></section>;
}

function OperationsRoles({context,onUpdated}){
 const [person,setPerson]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function update(user_id,enabled){setBusy(true);setError('');try{await missionAction('set_operations',{user_id,enabled});await onUpdated();setPerson('');}catch(e){setError(missionError(e));}finally{setBusy(false);}}
 return <details className="ms-role-settings"><summary>تعيين مسؤول العمليات <span>{context.people.filter(p=>p.operations_manager).length} مسؤول</span></summary><p>مسؤول العمليات يحدد عدد الموظفين لكل قسم ويوزع التكليفات ويراجع الانضمام ويعتمد تعذر التنفيذ</p><div className="ms-role-list">{context.people.filter(p=>p.operations_manager).map(p=><div key={p.id}><span>{personLabel(p)}</span><Button disabled={busy} onClick={()=>update(p.id,false)}>إزالة الصلاحية</Button></div>)}</div><form onSubmit={e=>{e.preventDefault();update(person,true);}} className="ms-inline-form"><label className="ms-field"><span>الحساب المسؤول عن العمليات</span><select required value={person} onChange={e=>setPerson(e.target.value)}><option value="">اختر موظفا أو حساب إدارة</option>{context.people.filter(p=>!p.operations_manager).map(p=><option key={p.id} value={p.id}>{personLabel(p)}</option>)}</select></label><Button type="submit" disabled={!person||busy}>تعيين مسؤول العمليات</Button></form><ErrorMessage message={error}/></details>;
}

function MissionCard({mission,onOpen,entry}){
 const done=(mission.departments||[]).reduce((sum,d)=>sum+(d.completed_count||0),0),count=(mission.departments||[]).reduce((sum,d)=>sum+(d.assigned_count||0),0);
 return <button type="button" className="ms-mission-card" onClick={()=>onOpen(mission.id)}><span className="ms-card-top"><span className="ms-number">مهمة {mission.number?`#${mission.number}`:''}</span><Badge status={entry?.assignment.status||mission.status}/></span><strong>{mission.title}</strong>{(mission.pending_joins>0||mission.unable_pending>0)&&<span className="ms-dept-tags">{mission.pending_joins>0&&<span>{mission.pending_joins} طلب انضمام</span>}{mission.unable_pending>0&&<span>{mission.unable_pending} طلب تعذر</span>}</span>}<span className="ms-card-description">{mission.description}</span><span className="ms-dept-tags">{entry?<span>{entry.department?.name}</span>:(mission.departments||[]).map(d=><span key={d.id}>{d.name}</span>)}</span><span className="ms-card-bottom"><span><CalendarDays size={15}/>{entry?.due_at?'التسليم: ':''}{when(entry?.due_at||mission.execution_at)}</span><span>{entry?'فتح التفاصيل':`${done} / ${count} منجز`}<ArrowLeft size={15}/></span></span></button>;
}

function PersonalPlanner({items,layout,onOpen}){
 const [week,setWeek]=useState(0),entries=personalEntries(items),days=weekDays(week);
 if(layout==='kanban')return <div className="ms-kanban">{[['invited','بانتظار الاستلام'],['working','قيد التنفيذ'],['unable_pending','بانتظار القرار'],['completed','تم الإنجاز']].map(([status,label])=>{const group=entries.filter(e=>e.assignment.status===status);return <section key={status}><header><h3>{label}</h3><span>{group.length}</span></header>{group.map(entry=><MissionCard key={entry.assignment.id} mission={entry.mission} entry={entry} onOpen={onOpen}/>)}{!group.length&&<p className="ms-muted ms-column-empty">لا توجد مهام في هذه المرحلة</p>}</section>;})}</div>;
 return <section className="ms-calendar"><div className="ms-section-head"><div><h3>جدول التنفيذ والتسليم</h3><p>{days[0].toLocaleDateString('ar-SA',{dateStyle:'medium'})} — {days[6].toLocaleDateString('ar-SA',{dateStyle:'medium'})}</p></div><div className="ms-actions"><Button aria-label="الأسبوع السابق" onClick={()=>setWeek(week-1)}><ChevronRight size={18}/></Button><Button onClick={()=>setWeek(0)}>هذا الأسبوع</Button><Button aria-label="الأسبوع التالي" onClick={()=>setWeek(week+1)}><ChevronLeft size={18}/></Button></div></div><div className="ms-week">{days.map(day=>{const key=localDay(day),scheduled=entries.filter(e=>localDay(e.execution_at)===key||localDay(e.due_at)===key);return <section key={key} className={key===localDay(new Date())?'ms-today':''}><header><span>{day.toLocaleDateString('ar-SA',{weekday:'long'})}</span><strong>{day.getDate()}</strong></header>{scheduled.map(entry=><button className="ms-calendar-event" type="button" key={entry.assignment.id} onClick={()=>onOpen(entry.mission.id)}><small>{localDay(entry.due_at)===key?'آخر موعد للتسليم':'موعد التنفيذ'}</small><strong>{entry.mission.title}</strong><span>{entry.department?.name}</span><Badge status={entry.assignment.status}/></button>)}{!scheduled.length&&<span className="ms-muted">لا توجد مواعيد</span>}</section>;})}</div></section>;
}

function DepartmentDistribution({department,detail,context,act,busy}){
 const [capacity,setCapacity]=useState(department.capacity??''),[selected,setSelected]=useState([]),[query,setQuery]=useState('');
 useEffect(()=>{setCapacity(department.capacity??'');},[department.capacity]);
 const assigned=new Set(detail.assignments.map(a=>a.user_id));
 const candidates=context.people.filter(p=>!assigned.has(p.id)&&`${p.name} ${p.job_title||''} ${p.email||''}`.toLowerCase().includes(query.toLowerCase()));
 return <details className="ms-distribution"><summary>توزيع فريق القسم <Users size={16}/></summary><form className="ms-inline-form" onSubmit={e=>{e.preventDefault();act('capacity',{department_id:department.id,capacity:Number(capacity)});}}><label className="ms-field"><span>عدد الموظفين المسموح</span><input type="number" min={Math.max(1,department.assigned_count||0)} max={100} step={1} required value={capacity} onChange={e=>setCapacity(e.target.value)}/></label><Button type="submit" disabled={busy}>حفظ العدد</Button></form><label className="ms-field"><span>اختيار الموظفين من الحسابات الحالية</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالاسم أو المسمى أو البريد"/></label><div className="ms-person-picker">{candidates.map(p=><label key={p.id}><input disabled={busy} type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,p.id]:old.filter(id=>id!==p.id))}/><span>{p.name}<small>{p.job_title||''}{p.departments?.includes(department.service_id)?' · عضو القسم':''}</small></span></label>)}{!candidates.length&&<p>لا توجد حسابات مطابقة</p>}</div><Button primary disabled={busy||!selected.length} onClick={async()=>{if(await act('invite',{department_id:department.id,user_ids:selected}))setSelected([]);}}>تكليف {selected.length||''} موظف</Button></details>;
}

function AssignmentProgress({assignment,department,act,busy}){
 const [note,setNote]=useState(''),[status,setStatus]=useState('working');
 if(assignment.status==='unable')return <p className="ms-notice">اعتمد الأوبريشن تعذر تنفيذك في {department?.name}</p>;
 return <div className="ms-my-assignment"><div className="ms-section-head"><h3>دورك في {department?.name}</h3><Badge status={assignment.status}/></div>{assignment.note&&<p>{assignment.note}</p>}{assignment.status==='invited'?<><p>راجع متطلبات القسم والمواعيد ثم أكد استلام المهمة</p><Button primary disabled={busy} onClick={()=>act('progress',{assignment_id:assignment.id,status:'working',note:''})}><Check size={17}/>الموافقة واستلام المهمة</Button></>:assignment.status==='working'?<form onSubmit={async e=>{e.preventDefault();if(await act('progress',{assignment_id:assignment.id,status,note})){setNote('');setStatus('working');}}}><div className="ms-form-grid"><label className="ms-field"><span>تحديث التنفيذ</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="working">باقي شغالين</option><option value="completed">تم الإنجاز</option><option value="unable_pending">تعذر التنفيذ</option></select></label><label className="ms-field"><span>{status==='unable_pending'?'سبب تعذر التنفيذ':'ملاحظة التنفيذ'}</span><textarea value={note} onChange={e=>setNote(e.target.value)} required={status!=='completed'} minLength={status!=='completed'?3:undefined} rows={2}/></label></div><Button primary type="submit" disabled={busy||(status!=='completed'&&note.trim().length<3)}>إرسال التحديث</Button><small className="ms-muted">{status==='unable_pending'?'يستمر تكليفك حتى اعتماد التعذر من الأوبريشن':'يصل التحديث إلى الأوبريشن والإدارة'}</small></form>:assignment.status==='unable_pending'?<p>طلب التعذر لدى الأوبريشن للمراجعة وسيصلك إشعار بالقرار</p>:<p>تم تسجيل إنجازك وإشعار المسؤولين</p>}</div>;
}

function ReviewRequest({request,department,kind,act,busy}){
 const [reason,setReason]=useState('');
 return <article className="ms-review"><div className="ms-section-head"><div><h4>{request.name||'عضو الفريق'}</h4><span className="ms-muted">{department?.name} · {kind==='join'?'طلب انضمام':'طلب تعذر التنفيذ'}</span></div><Badge status={kind==='join'?request.status:'unable_pending'}/></div>{kind==='join'&&<dl className="ms-person-details"><div><dt>المسمى الوظيفي</dt><dd>{request.job_title||'غير مسجل'}</dd></div><div><dt>البريد الإلكتروني</dt><dd dir="ltr">{request.email||'غير مسجل'}</dd></div><div><dt>الجوال</dt><dd dir="ltr">{request.phone||'غير مسجل'}</dd></div><div><dt>الأقسام الحالية</dt><dd>{request.department_names?.join(' · ')||'غير مسجل'}</dd></div></dl>}<p className="ms-preserve">{request.message||request.note||'لم تضف ملاحظة'}</p><label className="ms-field"><span>ملاحظة القرار <small>{kind==='join'?'مطلوبة للرفض بثلاثة أحرف على الأقل واختيارية للموافقة':'مطلوبة للموافقة أو الرفض بثلاثة أحرف على الأقل'}</small></span><input value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="ms-actions"><Button primary disabled={busy||(kind!=='join'&&reason.trim().length<3)} onClick={()=>act(kind==='join'?'review_join':'review_unable',{[kind==='join'?'join_id':'assignment_id']:request.id,decision:'approve',reason})}>موافقة</Button><Button disabled={busy||reason.trim().length<3} onClick={()=>act(kind==='join'?'review_join':'review_unable',{[kind==='join'?'join_id':'assignment_id']:request.id,decision:'reject',reason})}>رفض</Button></div></article>;
}

function JoinForm({detail,act,busy}){
 const [department,setDepartment]=useState(''),[message,setMessage]=useState('');
 return <form className="ms-join-form" onSubmit={e=>{e.preventDefault();act('join',{department_id:department,message});}}><h3>شارك في هذه المهمة</h3><p>يمكنك طلب الانضمام إلى أحد أقسام المهمة ويتولى الأوبريشن أو الإدارة مراجعة طلبك</p><div className="ms-form-grid"><label className="ms-field"><span>القسم المطلوب</span><select value={department} onChange={e=>setDepartment(e.target.value)} required><option value="">اختر القسم</option>{detail.departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label className="ms-field"><span>كيف ستساهم في المهمة</span><textarea required minLength={3} rows={2} value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000}/></label></div><Button primary type="submit" disabled={busy||message.trim().length<3}>إرسال طلب الانضمام</Button></form>;
}

function DraftPublication({detail,act,busy,onReload}){
 const [files,setFiles]=useState([]),[uploading,setUploading]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');
 async function upload(){setUploading(true);setError('');try{await attachFiles(detail.mission,files,setProgress,detail.attachments.length);setFiles([]);await onReload();}catch(e){setError(missionError(e));await onReload();}finally{setUploading(false);setProgress('');}}
 return <section className="ms-draft"><h3>المهمة محفوظة كمسودة</h3><p>أكمل المرفقات ثم انشر المهمة لإتاحتها للفريق وإشعار الأوبريشن</p><FileInput files={files} setFiles={setFiles} disabled={busy||uploading} existing={detail.attachments.length}/><div className="ms-actions"><Button disabled={!files.length||busy||uploading} onClick={upload}>رفع المرفقات</Button><Button primary disabled={busy||uploading||files.length>0} onClick={()=>act('publish',{})}>نشر المهمة</Button></div><p role="status">{progress}</p><ErrorMessage message={error}/></section>;
}

function MissionDetail({id,context,onBack,onChanged}){
 const [detail,setDetail]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[success,setSuccess]=useState(''),[editing,setEditing]=useState(false);
 const serial=useRef(0),heading=useRef(null);
 async function load(){const request=++serial.current;try{const data=await getMissionDetail(id);if(request===serial.current)setDetail({...data,departments:data.departments||[],assignments:data.assignments||[],joins:data.joins||[],attachments:data.attachments||[],events:data.events||[]});}catch(e){if(request===serial.current)setError(missionError(e));}finally{if(request===serial.current)setLoading(false);}}
 useEffect(()=>{setDetail(null);setError('');setLoading(true);load();heading.current?.focus();return ()=>{serial.current++;};},[id]);
 useEffect(()=>{if(detail&&!loading)heading.current?.focus();},[id,loading]);
 useMissionRefresh(load,!busy&&!editing);
 async function act(action,p){if(busy||!detail)return false;setBusy(true);setError('');setSuccess('');try{await missionAction(action,{id,version:detail.mission.version,...p});await load();onChanged();setSuccess('تم حفظ الإجراء وإشعار المعنيين');return true;}catch(e){setError(missionError(e));if(e?.message?.includes('version_conflict'))await load();return false;}finally{setBusy(false);}}
 const mission=detail?.mission,reviewer=context.admin||context.operations;
 if(editing&&detail)return <MissionComposer context={context} initialDetail={detail} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);load();onChanged();}}/>;
 return <section className="ms-detail"><div className="ms-detail-nav"><Button onClick={onBack}><ArrowRight size={17}/>كل المهام</Button><Button disabled={busy||loading} onClick={load}><RefreshCw size={16}/>تحديث التفاصيل</Button></div><ErrorMessage message={error}/>{loading&&<p role="status">جار تحميل تفاصيل المهمة</p>}{success&&<p className="ms-success" role="status">{success}</p>}{detail&&<><header className="ms-detail-heading"><div className="ms-card-top"><span className="ms-eyebrow">مهمة #{mission.number}</span><Badge status={mission.status}/></div><h2 ref={heading} tabIndex={-1}>{mission.title}</h2><p className="ms-preserve">{mission.description}</p><div className="ms-resource-links"><span><CalendarDays size={17}/>{when(mission.execution_at)}</span>{googleResource(mission.drive_url,'drive')&&<a href={googleResource(mission.drive_url,'drive')} target="_blank" rel="noopener noreferrer">Google Drive <ExternalLink size={15}/></a>}{googleResource(mission.map_url,'map')&&<a href={googleResource(mission.map_url,'map')} target="_blank" rel="noopener noreferrer">فتح الموقع في Google Maps <ExternalLink size={15}/></a>}</div></header>
 {mission.status==='draft'&&context.admin&&<><Button onClick={()=>setEditing(true)} disabled={busy}>تعديل بيانات المسودة والمواعيد</Button><DraftPublication detail={detail} act={act} busy={busy} onReload={load}/></>}
 <div className="ms-detail-columns"><div className="ms-detail-main"><section><h3 className="ms-section-title">الأقسام ومتطلبات التنفيذ <span>{detail.departments.length}</span></h3>{detail.departments.map(d=><article className="ms-department" key={d.id}><div className="ms-section-head"><h3>{d.name}</h3><span className="ms-muted">{d.assigned_count||0} / {d.capacity??'لم يحدد'} موظف</span></div><p className="ms-preserve">{d.requirements}</p><dl className="ms-dates"><div><dt>تاريخ التنفيذ</dt><dd>{when(d.execution_at)}</dd></div><div><dt>آخر موعد للتسليم</dt><dd>{when(d.due_at)}</dd></div></dl><div className="ms-team-members">{detail.assignments.filter(a=>a.department_id===d.id).map(a=><div key={a.id}><span>{a.name||'عضو الفريق'}</span><Badge status={a.status}/></div>)}{!detail.assignments.some(a=>a.department_id===d.id)&&<p className="ms-muted">بانتظار توزيع الموظفين من الأوبريشن</p>}</div>{context.operations&&mission.status==='published'&&<DepartmentDistribution department={d} detail={detail} context={context} act={act} busy={busy}/>}</article>)}</section>
 {detail.assignments.filter(a=>a.user_id===context.user_id).map(a=><AssignmentProgress assignment={a} department={detail.departments.find(d=>d.id===a.department_id)} key={a.id} act={act} busy={busy||mission.status!=='published'}/>)}
 {canRequestJoin(context,detail)&&<JoinForm detail={detail} act={act} busy={busy}/>}
 {detail.joins.filter(j=>j.user_id===context.user_id).map(j=><div className="ms-notice" key={j.id}><strong>طلب انضمامك إلى {detail.departments.find(d=>d.id===j.department_id)?.name}</strong> <Badge status={j.status}/>{j.reason&&<p>{j.reason}</p>}{j.status==='approved'&&<p>تم إدراجك ضمن فريق القسم أكد استلام المهمة لبدء التنفيذ</p>}</div>)}
 {reviewer&&detail.joins.some(j=>j.status==='pending')&&<section><h3 className="ms-section-title">طلبات الانضمام</h3>{detail.joins.filter(j=>j.status==='pending').map(j=><ReviewRequest key={j.id} request={j} department={detail.departments.find(d=>d.id===j.department_id)} kind="join" act={act} busy={busy}/>)}</section>}
 {context.operations&&detail.assignments.some(a=>a.status==='unable_pending')&&<section><h3 className="ms-section-title">طلبات تعذر التنفيذ</h3>{detail.assignments.filter(a=>a.status==='unable_pending').map(a=><ReviewRequest key={a.id} request={a} department={detail.departments.find(d=>d.id===a.department_id)} kind="unable" act={act} busy={busy}/>)}</section>}
 {reviewer&&mission.status==='published'&&<div className="ms-close-task"><h3>إتمام المهمة</h3><p>أغلق المهمة بعد إنجاز عمل كل قسم ومراجعة آخر التحديثات</p><Button disabled={busy||detail.joins.some(j=>j.status==='pending')||!detail.departments.length||detail.departments.some(d=>!detail.assignments.some(a=>a.department_id===d.id&&a.status==='completed'))||detail.assignments.some(a=>!['completed','unable'].includes(a.status))} onClick={()=>act('close',{})}><Check size={17}/>اعتماد اكتمال المهمة</Button></div>}
 </div><aside className="ms-detail-aside"><section><h3>مرفقات المهمة <span>{detail.attachments.length}</span></h3>{detail.attachments.map(file=><Button key={file.id} onClick={async()=>{try{await missionDownload(file);}catch(e){setError(missionError(e));}}}><FileText size={17}/><span>{file.filename}</span><ExternalLink size={14}/></Button>)}{!detail.attachments.length&&<p className="ms-muted">لم تضف مرفقات لهذه المهمة</p>}</section><section><h3>سجل التنفيذ</h3><ol className="ms-timeline">{detail.events.map(event=><li key={event.id}><strong>{missionEventNames[event.kind]||'تحديث المهمة'}</strong><span>{event.actor_name}</span>{eventDescription(event,detail,context)&&<p>{eventDescription(event,detail,context)}</p>}{event.note&&<p>{event.note}</p>}<time dateTime={event.created_at}>{when(event.created_at)}</time></li>)}</ol>{!detail.events.length&&<p className="ms-muted">لا توجد تحديثات بعد</p>}</section></aside></div></>}</section>;
}

export default function MissionWorkspace({user,initialMission=null,initialView='overview'}){
 const [context,setContext]=useState(null),[view,setView]=useState(initialView),[selected,setSelected]=useState(typeof initialMission==='object'?initialMission?.id:initialMission),[creating,setCreating]=useState(false),[board,setBoard]=useState(emptyBoard),[search,setSearch]=useState(''),[term,setTerm]=useState(''),[page,setPage]=useState(0),[layout,setLayout]=useState('list'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const boardRequest=useRef(0),loadedBoardKey=useRef('');
 async function refreshContext(){const data=await getMissionContext();setContext(previous=>{const next={...data,departments:data.departments||[],people:data.people||[]};return JSON.stringify(previous)===JSON.stringify(next)?previous:next;});}
 useMissionRefresh(refreshContext,Boolean(context));
 useMissionRefresh(()=>setRevision(x=>x+1),Boolean(context)&&!creating&&!selected);
 useEffect(()=>{let live=true;setContext(null);getMissionContext().then(data=>{if(live)setContext({...data,departments:data.departments||[],people:data.people||[]});}).catch(e=>{if(live){setError(missionError(e));setLoading(false);}});return ()=>{live=false;};},[user?.id]);
 useEffect(()=>{setView(initialView);setPage(0);setCreating(false);},[initialView]);
 useEffect(()=>{if(initialMission)setSelected(typeof initialMission==='object'?initialMission.id:initialMission);},[initialMission]);
 useEffect(()=>{if(!context)return;const request=++boardRequest.current;const boardKey=JSON.stringify([context.user_id,view,term,page,layout]);setLoading(loadedBoardKey.current!==boardKey);loadedBoardKey.current=boardKey;setError('');const actualView=view==='overview'?(context.admin?'overview':context.operations?'operations':'mine'):view;
  (async()=>{let data=await getMissionBoard(actualView,term,page);if(view==='mine'&&layout!=='list'){const all=[...(data.items||[])];let next=1;while(all.length<data.total){const part=await getMissionBoard('mine',term,next++);if(request!==boardRequest.current)return;if(!part.items?.length)break;all.push(...part.items);}data={...data,items:all};}if(request===boardRequest.current)setBoard({...data,items:data.items||[],stats:data.stats||{}});})().catch(e=>{if(request===boardRequest.current){setError(missionError(e));setBoard(emptyBoard);}}).finally(()=>{if(request===boardRequest.current)setLoading(false);});return ()=>{boardRequest.current++;};
 },[context,view,term,page,layout,revision]);
 const navigate=next=>{setView(next);setSelected(null);setCreating(false);setPage(0);setTerm('');setSearch('');};
 const open=id=>{setSelected(id);setCreating(false);};
 const reviewer=context?.admin||context?.operations;
 return <div className="ms-root" dir="rtl"><header className="ms-workspace-heading"><div><span className="ms-eyebrow">مساحة العمل · صيت</span><h1>{viewTitles[view]||viewTitles.overview}</h1><p>{context?.admin?'انشر المهمات واربط الأقسام وتابع التنفيذ من مكان واحد':context?.operations?'وزع الأدوار واضبط الأعداد وواكب تقدم الفريق':'اطلع على مهام الفريق ونظم عملك وشارك فيما تتقنه'}</p></div>{context?.admin&&<Button primary onClick={()=>{setCreating(true);setSelected(null);}}><Plus size={18}/>تسجيل مهمة</Button>}</header>
 <nav className="ms-tabs" aria-label="مساحات المهام">{[['overview','نظرة عامة'],['available','مهام متاحة'],['mine','مهامي'],...(reviewer?[['operations','متابعة الفريق'],['completed','المنجزة']]:[]),...(context?.admin?[['drafts','المسودات']]:[])].map(([key,label])=><button key={key} type="button" aria-current={view===key?'page':undefined} className={view===key?'is-active':''} onClick={()=>navigate(key)}>{label}</button>)}</nav>
 {!context?<><ErrorMessage message={error}/>{loading?<p role="status">جار تجهيز مساحة العمل</p>:<Button onClick={()=>{setError('');setLoading(true);refreshContext().catch(e=>{setError(missionError(e));setLoading(false);});}}>إعادة المحاولة</Button>}</>:creating?<MissionComposer context={context} onClose={()=>setCreating(false)} onSaved={id=>{setCreating(false);setSelected(id);setRevision(x=>x+1);}}/>:selected?<MissionDetail id={selected} context={context} onBack={()=>setSelected(null)} onChanged={()=>setRevision(x=>x+1)}/>:<>
 {view==='overview'&&<><div className="ms-stats">{[['published','مهام منشورة','available'],['mine','مهامي','mine'],['invited','بانتظار استلامك','mine'],...(reviewer?[['pending_joins','طلبات انضمام','operations'],['unable_pending','طلبات تعذر','operations']]:[])].map(([key,label,target])=><button type="button" key={key} onClick={()=>navigate(target)}><span>{label}</span><strong>{board.stats[key]??0}</strong><ArrowLeft size={17}/></button>)}</div><div className="ms-priority"><span className="ms-eyebrow">خطوتك التالية</span><h2>{context.operations?'ابدأ بتوزيع الفرق وراجع طلبات الانضمام':context.admin?'حدد وجهة الفريق بمهمة واضحة':'استلم مهمتك وشارك الفريق تحديثك'}</h2><p>{context.operations?'لكل قسم عدد محدد وموظفون مكلفون وتحديثات تستحق المتابعة':context.admin?'ضع المطلوب والمواعيد واترك توزيع الأدوار ومتابعة التنفيذ للأوبريشن':'مواعيد التنفيذ والتسليم وتفاصيل دورك موجودة في مساحة مهامك'}</p><Button onClick={()=>context.admin?setCreating(true):navigate(context.operations?'operations':'mine')}>{context.admin?'تسجيل مهمة جديدة':context.operations?'متابعة الفريق':'الانتقال إلى مهامي'}<ArrowLeft size={16}/></Button></div>{context.admin&&<OperationsRoles context={context} onUpdated={refreshContext}/>}</>}
 <div className="ms-board-toolbar"><form className="ms-search" onSubmit={e=>{e.preventDefault();setTerm(search.trim());setPage(0);}}><label><span className="ms-sr">البحث عن مهمة</span><Search size={18} aria-hidden="true"/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث عن مهمة بالعنوان"/></label><Button type="submit">بحث</Button></form><div className="ms-actions">{view==='mine'&&<div className="ms-view-switch" aria-label="طريقة عرض مهامي">{[['list','قائمة',List],['kanban','كانبان',LayoutGrid],['calendar','جدول',CalendarDays]].map(([key,label,Icon])=><button key={key} type="button" aria-pressed={layout===key} onClick={()=>{setLayout(key);setPage(0);}}><Icon size={16}/>{label}</button>)}</div>}<Button disabled={loading} aria-label="تحديث المهام" onClick={()=>setRevision(x=>x+1)}><RefreshCw size={17}/></Button></div></div><ErrorMessage message={error}/>
 {loading?<div className="ms-loading" role="status">جار تحميل المهام والمواعيد</div>:!board.items.length?<Empty>{term?'لا توجد مهام مطابقة للبحث':view==='mine'?'ستظهر هنا المهام التي كلفت بها ومواعيد تنفيذها':view==='operations'?'لا توجد مهام تحتاج المتابعة حاليا':'لا توجد مهام منشورة بعد'}</Empty>:view==='mine'&&layout!=='list'?<PersonalPlanner items={board.items} layout={layout} onOpen={open}/>:<><div className="ms-mission-list">{board.items.map(m=><MissionCard key={m.id} mission={m} onOpen={open}/>)}</div><div className="ms-pagination"><span>{board.total} مهمة · صفحة {page+1}</span><div className="ms-actions"><Button disabled={page===0} onClick={()=>setPage(page-1)}>السابق</Button><Button disabled={(page+1)*24>=board.total} onClick={()=>setPage(page+1)}>التالي</Button></div></div></>}
 </>}
 </div>;
}
