import test from 'node:test';
import assert from 'node:assert/strict';
import {googleResource,canRequestJoin,createPayload,personalEntries,weekDays,localDay,eventDescription} from '../src/missions/mission-model.js';
test('Google resource links reject executable and deceptive destinations',()=>{assert.equal(googleResource('javascript:alert(1)','map'),'');assert.equal(googleResource('https://google.com.evil.test/maps','map'),'');assert.equal(googleResource('https://evil.test@google.com/maps','map'),'');assert.equal(googleResource('https://google.com/search?q=maps','map'),'');assert.equal(googleResource('https://maps.app.goo.gl/example','map'),'https://maps.app.goo.gl/example');assert.equal(googleResource('https://drive.google.com/file/d/example','drive'),'https://drive.google.com/file/d/example');});
test('joining excludes members of any mission department and active assignments',()=>{const detail={mission:{status:'published'},departments:[{service_id:'a'},{service_id:'b'}],assignments:[],joins:[]};assert.equal(canRequestJoin({user_id:'me',department_ids:['b']},detail),false);assert.equal(canRequestJoin({user_id:'me',department_ids:['c']},detail),true);assert.equal(canRequestJoin({user_id:'me',department_ids:[]},{...detail,joins:[{user_id:'me',status:'pending'}]}),false);assert.equal(canRequestJoin({user_id:'me',department_ids:[]},{...detail,assignments:[{user_id:'me',status:'invited'}]}),false);});
test('mission payload validates per-department dates and normalizes timezone',()=>{const form={title:' مهمة ',description:' وصف تفصيلي للمهمة ',drive_url:'',map_url:'',execution_at:'2026-09-21T10:00',departments:[{service_id:'a',requirements:' مطلوب ',execution_at:'2026-09-21T10:00',due_at:'2026-09-21T12:00'}]};const payload=createPayload(form,'key');assert.equal(payload.title,'مهمة');assert.equal(payload.departments[0].requirements,'مطلوب');assert.match(payload.execution_at,/Z$/);assert.throws(()=>createPayload({...form,departments:[{...form.departments[0],due_at:'2026-09-20T10:00'}]},'key'),/mission_department_dates/);assert.throws(()=>createPayload({...form,departments:[{...form.departments[0],execution_at:'2026-09-20T10:00'}]},'key'),/mission_department_dates/);});
test('personal calendar keeps department dates and local week boundaries',()=>{const items=[{id:'m',execution_at:'2026-09-20',departments:[{id:'d',execution_at:'2026-09-21',due_at:'2026-09-23'}],mine:[{id:'a',department_id:'d',status:'working'}]}];const entries=personalEntries(items);assert.equal(entries[0].execution_at,'2026-09-21');assert.equal(entries[0].due_at,'2026-09-23');const days=weekDays(1,new Date(2026,8,21,12));assert.equal(days.length,7);assert.equal(days[0].getDay(),0);assert.equal(localDay(days[0]),'2026-09-27');});
test('rejected join and ended assignment do not offer unsupported reapplication',()=>{const detail={mission:{status:'published'},departments:[{service_id:'a'}],assignments:[],joins:[{user_id:'me',status:'rejected'}]},context={user_id:'me',department_ids:[]};assert.equal(canRequestJoin(context,detail),false);assert.equal(canRequestJoin(context,{...detail,joins:[],assignments:[{user_id:'me',status:'unable'}]}),false);});
test('history explains assignment status and department instead of exposing IDs',()=>{const detail={assignments:[{id:'a',department_id:'d',name:'أحمد'}],departments:[{id:'d',name:'التصوير'}],joins:[]};assert.equal(eventDescription({details:{assignment_id:'a',status:'working'}},detail,{people:[]}),'التصوير · أحمد · قيد التنفيذ');});
