import React from 'react';
import {ArrowLeft,ArrowRight,CalendarDays} from 'lucide-react';
import {dateLabel,riyadhDate} from '../shared/date-only';
import {calendarDays,shiftMonth,timelineSpan,workloadGroups} from './planner-views';
import {plannerBuckets} from './task-planner';

const status=task=>plannerBuckets.find(bucket=>bucket.id===task.bucket)?.label||'قيد التنفيذ';
const monthLabel=month=>new Intl.DateTimeFormat('ar-SA',{month:'long',year:'numeric',calendar:'gregory',timeZone:'Asia/Riyadh'}).format(new Date(`${month}-01T12:00:00+03:00`));
export function PlannerPeriod({month,onMonth}){
 return <div className="w-planner-period"><h4>{monthLabel(month)}</h4><div><button type="button" aria-label="الشهر السابق" onClick={()=>onMonth(shiftMonth(month,-1))}><ArrowRight size={16}/></button><button type="button" onClick={()=>onMonth(riyadhDate().slice(0,7))}>الشهر الحالي</button><button type="button" aria-label="الشهر التالي" onClick={()=>onMonth(shiftMonth(month,1))}><ArrowLeft size={16}/></button></div></div>;
}
function TaskIdentity({task,onOpen}){
 return <div className="w-planner-row-identity"><button type="button" onClick={()=>onOpen(task.request_id,task.part_id)}>{task.request_title}</button><span>{task.client_name}<small>طلب <bdi>{task.request_number}</bdi></small></span></div>;
}
function TaskState({task}){return <span className={`w-planner-state is-${task.bucket}`}><i aria-hidden="true"/>{status(task)}</span>;}
function RowActions({task,onOpen,onSchedule}){
 return <div className="w-planner-row-actions"><button type="button" onClick={()=>onOpen(task.request_id,task.part_id)}>فتح المهمة<ArrowLeft size={14}/></button>{task.can_reschedule&&!task.pending_due_change&&<button type="button" aria-label={`تعديل موعد ${task.request_title}`} onClick={()=>onSchedule(task)}><CalendarDays size={16}/><span>الموعد</span></button>}</div>;
}
export function PlannerList({tasks,onOpen,onSchedule,table=false,compact=false}){
 if(table&&!compact)return <div className="w-planner-table-wrap"><table className="w-planner-table"><caption className="w-planner-sr">المهام الشخصية ومواعيد التسليم المعتمدة</caption><thead><tr><th scope="col">المهمة والعميل</th><th scope="col">القسم</th><th scope="col">الحالة</th><th scope="col">الأولوية</th><th scope="col">موعد التسليم</th><th scope="col">الإجراءات</th></tr></thead><tbody>{tasks.map(task=><tr key={task.part_id}><td><TaskIdentity task={task} onOpen={onOpen}/></td><td>{task.department}</td><td><TaskState task={task}/></td><td className={task.priority==='urgent'?'w-danger':''}>{task.priority==='urgent'?'مستعجل':'عادي'}</td><td><time dateTime={task.due_at||undefined}>{dateLabel(task.due_at??null)}</time>{task.pending_due_change&&<small className="w-planner-pending-inline">تأجيل بانتظار الإدارة</small>}</td><td><RowActions task={task} onOpen={onOpen} onSchedule={onSchedule}/></td></tr>)}</tbody></table></div>;
 return <div className="w-planner-list">{tasks.map(task=><article key={task.part_id} className={`w-planner-row is-${task.bucket}`}><TaskIdentity task={task} onOpen={onOpen}/><div className="w-planner-row-meta"><span>{task.department}</span><TaskState task={task}/><span className={task.priority==='urgent'?'w-danger':''}>{task.priority==='urgent'?'مستعجل':'عادي'}</span></div><div className="w-planner-row-date"><small>موعد التسليم</small><time dateTime={task.due_at||undefined}>{dateLabel(task.due_at??null)}</time>{task.pending_due_change&&<small className="w-planner-pending-inline">تأجيل بانتظار الإدارة</small>}</div><RowActions task={task} onOpen={onOpen} onSchedule={onSchedule}/></article>)}</div>;
}
export function PlannerCalendar({tasks,month,onMonth,day,onDay,compact,renderTask,onOpen}){
 const days=calendarDays(month),today=riyadhDate(),byDay=new Map();
 for(const task of tasks){const date=riyadhDate(task.due_at??null);if(date)byDay.set(date,[...(byDay.get(date)||[]),task]);}
 const selected=byDay.get(day)||[],undated=tasks.filter(task=>!task.due_at);
 return <><PlannerPeriod month={month} onMonth={onMonth}/><div className="w-planner-calendar" aria-label="تقويم مواعيد تسليم المهام"><div className="w-planner-weekdays">{['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'].map(name=><span key={name}>{name}</span>)}</div><div className="w-planner-month-grid">{days.map(cell=>{const entries=byDay.get(cell.date)||[];return <div key={cell.date} className={`w-planner-calendar-day ${cell.inMonth?'':'is-outside'} ${cell.date===today?'is-today':''} ${cell.date===day?'is-selected':''}`}><button type="button" className="w-planner-day-select" aria-pressed={cell.date===day} aria-label={`${dateLabel(cell.date)} عدد المهام ${entries.length}`} onClick={()=>onDay(cell.date)}><bdi>{Number(cell.date.slice(-2))}</bdi>{compact&&entries.length>0&&<small>{entries.length}</small>}</button>{!compact&&entries.slice(0,3).map(task=><button className={`w-planner-calendar-task is-${task.bucket}`} key={task.part_id} type="button" onClick={()=>onOpen(task.request_id,task.part_id)}><span>{task.request_title}</span><small>{task.department}</small></button>)}{!compact&&entries.length>3&&<button className="w-planner-day-more" type="button" onClick={()=>onDay(cell.date)}>عرض {entries.length} مهام</button>}</div>;})}</div></div><section className="w-planner-selected-day" aria-label="مهام اليوم المحدد"><h4>{dateLabel(day)}<bdi>{selected.length}</bdi></h4>{selected.length?<div className="w-planner-date-tasks">{selected.map(renderTask)}</div>:<p className="w-planner-empty">لا توجد مواعيد تسليم في هذا اليوم</p>}</section>{undated.length>0&&<details className="w-planner-undated"><summary>مهام لم يحدد موعدها <bdi>{undated.length}</bdi></summary><div className="w-planner-date-tasks">{undated.map(renderTask)}</div></details>}</>;
}
export function PlannerTimeline({tasks,month,onMonth,onOpen,compact,renderTask}){
 const days=calendarDays(month).filter(day=>day.inMonth),start=days[0].date,end=days.at(-1).date;
 const rows=tasks.map(task=>({task,span:timelineSpan(task,start,end)})).filter(row=>row.span);
 return <><PlannerPeriod month={month} onMonth={onMonth}/><p className="w-planner-view-hint">من استلام المهمة إلى موعدها المعتمد والموعد وحده يظهر للمهام التي لم تسجل بداية استلامها</p>{!rows.length?<p className="w-planner-empty">لا توجد مهام ضمن هذا النطاق الزمني</p>:compact?<div className="w-planner-mobile-timeline">{rows.map(({task})=><section key={task.part_id}><div><span>{task.accepted_at?`استلمت ${dateLabel(task.accepted_at)}`:'لم يسجل تاريخ الاستلام'}</span><span>التسليم {dateLabel(task.due_at??null)}</span></div>{renderTask(task)}</section>)}</div>:<div className="w-planner-timeline"><div className="w-planner-timeline-head"><span>المهمة</span><div>{days.map(day=><bdi key={day.date}>{Number(day.date.slice(-2))}</bdi>)}</div></div>{rows.map(({task,span})=><div className="w-planner-timeline-row" key={task.part_id}><TaskIdentity task={task} onOpen={onOpen}/><div className="w-planner-timeline-track" style={{'--planner-days':days.length}}><button type="button" className={`w-planner-time-bar is-${task.bucket}`} style={{insetInlineStart:`${span.left}%`,width:`${Math.max(span.width,100/days.length)}%`}} aria-label={`${task.request_title} موعد التسليم ${dateLabel(task.due_at??null)} ${status(task)}`} onClick={()=>onOpen(task.request_id,task.part_id)}><span>{dateLabel(task.due_at??null)}</span></button></div></div>)}</div>}</>;
}
export function PlannerWorkload({tasks,renderTask}){
 const groups=workloadGroups(tasks),maximum=Math.max(1,...groups.map(group=>group.total));
 return <div className="w-planner-workload"><p className="w-planner-view-hint">توزيع مهامك الشخصية حسب القسم مع عدد المهام المفتوحة والمتأخرة</p>{groups.map(group=><details key={group.department} className="w-planner-workload-group"><summary><span>{group.department}<small>{group.active} مفتوحة{group.overdue>0&&<b className="w-danger">{group.overdue} متأخرة</b>}{group.undated>0&&<span>{group.undated} دون موعد</span>}</small></span><span className="w-planner-load-bar" aria-hidden="true"><i style={{width:`${group.total/maximum*100}%`}}/></span><bdi>{group.total}</bdi></summary><div className="w-planner-date-tasks">{tasks.filter(task=>task.department===group.department).map(renderTask)}</div></details>)}</div>;
}
