import React,{useEffect,useMemo,useRef,useState} from 'react';
import {BarChart3,Building2,Camera,Code2,Film,Megaphone,MessageSquare,PackageCheck,Palette,PenTool,Plus,Printer,RefreshCw,Search,ShoppingBag,SlidersHorizontal,Sparkles} from 'lucide-react';
import {repository,workError} from './data';
import {getCatalog} from '../data/catalog-gateway';
import {useSessionState} from '../shared/session-state';
import './service-catalog.css';

const iconMap={'building-2':Building2,palette:Palette,'pen-tool':PenTool,camera:Camera,film:Film,printer:Printer,megaphone:Megaphone,code:Code2,'message-square':MessageSquare,'shopping-bag':ShoppingBag,chart:BarChart3,'package-check':PackageCheck,sparkles:Sparkles};
const iconLabels={'building-2':'قسم',palette:'تصميم','pen-tool':'كتابة',camera:'تصوير',film:'مونتاج',printer:'طباعة',megaphone:'تواصل',code:'تقنية','message-square':'محادثات','shopping-bag':'تجارة',chart:'تحليل','package-check':'تسليم',sparkles:'إبداع'};
const newService={name:'',slug:'',category:'خدمات صيت',description:'',icon:'sparkles',active:false,client_visible:true,target_hours:72,default_effort_points:5,sort_order:100};
const targetLabel=minutes=>minutes>=1440&&minutes%1440===0?`${minutes/1440} أيام عمل`:`${Math.max(1,Math.round(minutes/60))} ساعة عمل`;

export default function ServiceCatalog({editable=false,onRequest,onDepartments}){
 const [services,setServices]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [draft,setDraft,draftState]=useSessionState('services.editor',null,{validate:value=>value===null||Boolean(value&&typeof value.name==='string'&&typeof value.slug==='string'&&typeof value.category==='string'&&typeof value.description==='string')});
 const [search,setSearch]=useSessionState('services.search','',{validate:value=>typeof value==='string'}),[category,setCategory]=useSessionState('services.category','all',{validate:value=>typeof value==='string'}),[sortBy,setSortBy]=useSessionState('services.sort','order',{validate:value=>['order','name','target','effort'].includes(value)});
 const catalogTitle=useRef(null),editorName=useRef(null),returnFocus=useRef(null),editorDialog=useRef(null);
 const [setupId,setSetupId]=useSessionState('services.setupId',null,{validate:value=>value===null||typeof value==='string'});
 const editorOpen=editable&&Boolean(draft);
 useEffect(()=>{if(editorOpen){editorDialog.current?.showModal();editorName.current?.focus();}},[editorOpen]);
 const fetchServices=()=>editable?repository.serviceCatalog(true):getCatalog('services');
 async function load(){setLoading(true);setError('');try{setServices(await fetchServices());}catch(e){setError(workError(e));}finally{setLoading(false);}}
 useEffect(()=>{let live=true;setLoading(true);fetchServices().then(rows=>{if(live){setServices(rows);setError('');}}).catch(e=>{if(live)setError(workError(e));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[editable]);
 const categories=useMemo(()=>[...new Set(services.map(service=>service.category||'خدمات صيت'))].sort((left,right)=>left.localeCompare(right,'ar')),[services]);
 const filteredServices=useMemo(()=>{
  const term=search.trim().toLocaleLowerCase('ar');
  return services.filter(service=>{
   const serviceCategory=service.category||'خدمات صيت';
   const matchesSearch=!term||[service.name,service.description,serviceCategory].some(value=>String(value||'').toLocaleLowerCase('ar').includes(term));
   return matchesSearch&&(category==='all'||serviceCategory===category);
  }).sort((left,right)=>{
   if(sortBy==='name')return String(left.name||'').localeCompare(String(right.name||''),'ar');
   if(sortBy==='target')return Number(left.default_target_minutes||4320)-Number(right.default_target_minutes||4320)||String(left.name||'').localeCompare(String(right.name||''),'ar');
   if(sortBy==='effort')return Number(right.default_effort_points||5)-Number(left.default_effort_points||5)||String(left.name||'').localeCompare(String(right.name||''),'ar');
   return Number(left.sort_order??100)-Number(right.sort_order??100)||String(left.name||'').localeCompare(String(right.name||''),'ar');
  });
 },[category,search,services,sortBy]);
 const groups=useMemo(()=>Array.from(filteredServices.reduce((map,service)=>{const serviceCategory=service.category||'خدمات صيت';if(!map.has(serviceCategory))map.set(serviceCategory,[]);map.get(serviceCategory).push(service);return map;},new Map())),[filteredServices]);
 const activeFilters=Boolean(search||category!=='all'||sortBy!=='order');
 function clearFilters(){setSearch('');setCategory('all');setSortBy('order');}
 function edit(service){returnFocus.current=document.activeElement;setNotice('');setError('');setDraft(service?{...service,target_hours:Math.max(.5,Number(service.default_target_minutes||4320)/60)}:{...newService});}
 function closeEditor(){draftState.clear();requestAnimationFrame(()=>{const target=returnFocus.current?.isConnected?returnFocus.current:catalogTitle.current;target?.focus();returnFocus.current=null;});}
 async function save(event){
  event.preventDefault();if(busy||!editable)return;setBusy(true);setError('');setNotice('');
  try{
   const saved=await repository.saveService({...(draft.id?{id:draft.id,version:draft.version}:{}),name:draft.name.trim(),slug:draft.slug.trim().toLowerCase(),category:draft.category.trim(),description:draft.description.trim(),icon:draft.icon,active:draft.id?draft.active:false,...(typeof draft.client_visible==='boolean'?{client_visible:draft.client_visible}:{}),default_target_minutes:Math.round(Number(draft.target_hours)*60),default_effort_points:Number(draft.default_effort_points),sort_order:Number(draft.sort_order)});
   closeEditor();setSetupId(saved.requires_department_setup?saved.id:null);setNotice(saved.requires_department_setup?'تم حفظ الخدمة كمسودة أكمل مسؤوليات القسم وفريقه لتفعيلها':'تم حفظ إعدادات الخدمة');await load();
  }catch(e){setError(workError(e));}finally{setBusy(false);}
 }
 return <section className="svc-catalog" dir="rtl" aria-labelledby="service-catalog-title">
  <header className="svc-heading"><div><span className="a-eyebrow">دليل القدرات</span><h2 ref={catalogTitle} tabIndex={-1} id="service-catalog-title">خدمات تعمل من الطلب إلى التسليم</h2><p>كل خدمة مرتبطة بوقت مستهدف ووزن جهد ومسار واضح للفريق</p></div>{editable&&<button type="button" className="a-primary" onClick={()=>edit(null)}><Plus size={18}/>إضافة خدمة احترافية</button>}</header>
  {notice&&<p className="svc-notice" role="status">{notice}</p>}
  {setupId&&onDepartments&&<button type="button" className="svc-setup-link" onClick={()=>onDepartments(setupId)}>إكمال إعداد القسم وفريقه</button>}
  {error&&<div className="svc-error" role="alert"><span>{error}</span><button type="button" onClick={load}>إعادة المحاولة</button></div>}
  {!loading&&services.length>0&&<section className="svc-filters" aria-label="البحث وتصفية دليل الخدمات"><div className="svc-filter-heading"><span><SlidersHorizontal size={17} aria-hidden="true"/>استكشاف الخدمات</span><span role="status">{filteredServices.length} من {services.length} خدمة</span></div><div className="svc-filter-grid"><label className="svc-filter-search"><span><Search size={16} aria-hidden="true"/>البحث</span><input type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="اسم الخدمة أو وصفها"/></label><label><span>التصنيف</span><select value={category} onChange={event=>setCategory(event.target.value)}><option value="all">كل التصنيفات</option>{categories.map(item=><option value={item} key={item}>{item}</option>)}</select></label><label><span>الترتيب</span><select value={sortBy} onChange={event=>setSortBy(event.target.value)}><option value="order">الترتيب المعتمد</option><option value="name">اسم الخدمة</option><option value="target">الأسرع تنفيذا</option><option value="effort">وزن الجهد الأعلى</option></select></label></div>{activeFilters&&<button type="button" className="svc-clear-filters" onClick={clearFilters}>مسح التصفية</button>}</section>}
  {loading?<div className="svc-loading" role="status"><RefreshCw size={22}/><span>جار تجهيز دليل الخدمات</span></div>:!services.length?<div className="svc-empty"><Sparkles size={26}/><h3>دليل الخدمات قيد التجهيز</h3><p>ستظهر الخدمات المفعلة هنا فور اعتمادها</p></div>:!filteredServices.length?<div className="svc-empty" role="status"><Search size={26}/><h3>لا توجد خدمات مطابقة</h3><p>غيّر البحث أو التصنيف لعرض خدمات أخرى</p><button type="button" onClick={clearFilters}>عرض كل الخدمات</button></div>:groups.map(([category,items])=><section className="svc-group" key={category} aria-labelledby={`svc-${items[0].id}`}><div className="svc-group-title"><span>{String(items.length).padStart(2,'0')}</span><h3 id={`svc-${items[0].id}`}>{category}</h3></div><div className="svc-grid">{items.map(service=>{const Icon=iconMap[service.icon]||Sparkles;return <article className={!service.active?'is-inactive':''} key={service.id}><div className="svc-icon"><Icon size={22}/></div><div className="svc-copy"><div className="svc-title"><h4>{service.name}</h4>{!service.active&&<span>غير مفعلة</span>}</div><p>{service.description||'خدمة متخصصة مرتبطة مباشرة بمسار الطلب والتنفيذ'}</p><dl><div><dt>الوقت المستهدف</dt><dd>{targetLabel(service.default_target_minutes||4320)}</dd></div><div><dt>وزن الجهد</dt><dd>{service.default_effort_points||5} نقاط</dd></div></dl></div><footer>{editable?<button type="button" onClick={()=>edit(service)}>تعديل إعدادات الخدمة</button>:onRequest&&service.active?<button type="button" onClick={()=>onRequest(service)}>ابدأ طلب هذه الخدمة</button>:null}</footer></article>})}</div></section>)}
  {editorOpen&&<dialog ref={editorDialog} className="svc-editor-dialog" onCancel={event=>{event.preventDefault();if(!busy)closeEditor();}} aria-labelledby="service-editor-title"><form className="svc-editor" onSubmit={save} aria-labelledby="service-editor-title"><header><div><span className="a-eyebrow">إعداد مسار الخدمة</span><h3 id="service-editor-title">{draft.id?'تعديل الخدمة':'إضافة خدمة احترافية'}</h3></div><button type="button" onClick={closeEditor} disabled={busy}>إغلاق</button></header>{error&&<p role="alert" className="svc-error">{error}</p>}{!draft.id&&<p className="svc-editor-hint">تحفظ الخدمة كمسودة ثم تحدد مسؤوليات القسم ومسؤوله وفريقه قبل التفعيل</p>}<fieldset className="svc-fields" disabled={busy}><label>اسم الخدمة<input ref={editorName} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required minLength={2} maxLength={100}/></label><label>المعرف الإنجليزي<input dir="ltr" value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={90} placeholder="service-name"/></label><label>التصنيف<input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} required minLength={2} maxLength={80}/></label><label>رمز العرض<select value={draft.icon} onChange={e=>setDraft({...draft,icon:e.target.value})}>{Object.keys(iconMap).map(icon=><option value={icon} key={icon}>{iconLabels[icon]}</option>)}</select></label><label className="svc-wide">وصف الخدمة<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} maxLength={600} rows={3}/></label><label>الساعات المستهدفة<input type="number" value={draft.target_hours} onChange={e=>setDraft({...draft,target_hours:e.target.value})} required min="0.5" max="8760" step="0.5"/></label><label>وزن الجهد<input type="number" value={draft.default_effort_points} onChange={e=>setDraft({...draft,default_effort_points:e.target.value})} required min="0.5" max="100" step="0.5"/></label><label>ترتيب العرض<input type="number" value={draft.sort_order} onChange={e=>setDraft({...draft,sort_order:e.target.value})} required min="0" max="10000"/></label><label className="svc-check"><input type="checkbox" checked={draft.active} disabled={!draft.id} onChange={e=>setDraft({...draft,active:e.target.checked})}/>الخدمة مفعلة</label></fieldset><button className="a-primary" disabled={busy}>{busy?'جار حفظ الخدمة':'حفظ وربط الخدمة'}</button></form></dialog>}
 </section>;
}
