// Isolated PostgreSQL Actual RPC definitions and migrations No live data writes
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {PGlite} from '../../.tools/sql-check/node_modules/@electric-sql/pglite/dist/index.js';
const fixture=readFileSync('tests/sql/routing-decision-feedback.mjs','utf8');
const start=fixture.indexOf('const source='),end=fixture.indexOf('const version=');
assert(start>=0&&end>start);
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const db=await new AsyncFunction('PGlite','readFileSync','assert',fixture.slice(start,end)+'return db;')(PGlite,readFileSync,assert);
const sql=file=>readFileSync('supabase/migrations/'+file,'utf8');
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const query=async(q,args=[])=>(await db.query(q,args)).rows;
const as=async n=>query("select set_config('test.uid',$1,false)",[n?id(n):'']);
const version=async()=>(await query('select version from work_requests where id=$1',[id(10)]))[0].version;
await db.exec(sql('20260920100037_lock_confirmed_task_routing.sql'));
await db.exec(sql('20260920100438_preserve_confirmed_routing_after_other_decisions.sql'));
const live=JSON.parse(readFileSync('.tools/department-cards-live-functions.json','utf8'));
for(const row of live.filter(row=>['work_action','work_output_action','work_request_detail','work_team_overview'].includes(row.name)))await db.exec(row.definition);
await db.exec(`create or replace function provision_private.allowed(text) returns boolean language sql as $$select provision_private.work_manager()$$;
 create or replace function provision_private.work_lead(uuid) returns boolean language sql as $$select exists(select 1 from public.work_memberships where user_id=auth.uid() and service_id=$1 and member_role='lead')$$;`);
await db.exec(sql('20260920102507_department_cards_metrics_monthly_awards.sql'));
await db.exec(sql('20260920102942_department_output_distribution_queue.sql'));
await as(2);
await assert.rejects(()=>query('select work_department_performance(current_date,current_date)'),/forbidden/);
await assert.rejects(()=>query('select work_employee_of_month()'),/forbidden/);
await as(1);await assert.rejects(()=>query('select work_employee_of_month()'),/forbidden/);
await as(6);await assert.rejects(()=>query('select work_department_performance(current_date,current_date+1)'),/invalid_period/);
// Output distribution uses current eligible department membership
await query("update work_memberships set member_role='lead' where user_id=$1 and service_id=$2",[id(3),id(21)]);
await query('insert into work_memberships(user_id,service_id) values($1,$2)',[id(7),id(21)]);
await as(2);
const request={request_id:id(10),part_id:id(30),version:await version(),submission_key:id(500),outputs:[{service_id:id(21),reason:'مخرجات مطلوبة للاختبار'}]};
await query("select work_output_action('request_outputs',$1::jsonb)",[JSON.stringify(request)]);
const child=(await query('select * from work_parts where output_parent_id=$1',[id(30)]))[0];
assert.equal(child.assignee_id,id(3));assert.equal(child.output_distribution_pending,true);
const action=async(name,fields)=>query('select work_action($1,$2::jsonb)',[name,JSON.stringify({request_id:id(10),part_id:child.id,version:await version(),...fields})]);
await as(3);await assert.rejects(()=>action('accept',{due_at:'2028-01-01T20:59:59Z'}),/output_distribution_required/);
await assert.rejects(()=>action('delegate',{assignee_id:id(2)}),/invalid_assignment/);
await as(7);await assert.rejects(()=>action('delegate',{assignee_id:id(7)}),/forbidden/);
await as(3);await action('delegate',{assignee_id:id(7)});
let assigned=(await query('select * from work_parts where id=$1',[child.id]))[0];
assert.equal(assigned.assignee_id,id(7));assert.equal(assigned.output_distribution_pending,false);assert.equal(assigned.accepted_at,null);
assert.equal(assigned.performance_eligible,true,'initial distribution gives credit to the performing employee');
// Single-person department is immediately actionable by its lead
await query("update work_memberships set member_role='lead' where user_id=$1 and service_id=$2",[id(7),id(22)]);
await as(2);await query("select work_output_action('request_outputs',$1::jsonb)",[JSON.stringify({...request,version:await version(),submission_key:id(501),outputs:[{service_id:id(22),reason:'مخرجات القسم الفردي'}]})]);
assert.equal((await query('select output_distribution_pending from work_parts where output_parent_id=$1 and service_id=$2',[id(30),id(22)]))[0].output_distribution_pending,false);
// Department membership and account profile use the same canonical membership table
await db.exec(`alter table work_services add column if not exists version integer not null default 1;
 alter table work_services add column if not exists updated_at timestamptz default now();
 alter table work_services add column if not exists slug text;
 alter table work_services add column if not exists category text;
 alter table work_services add column if not exists description text;
 alter table work_services add column if not exists icon text;
 create table provision_private.audit(actor uuid,effective_user uuid,action text,details jsonb);
 create table work_department_responsibilities(id uuid default gen_random_uuid(),service_id uuid,item text,sort_order integer);
 create table work_department_tasks(id uuid default gen_random_uuid(),service_id uuid,item text,sort_order integer);`);
const extract=(source,name)=>{let i=source.indexOf('create or replace function '+name+'(');if(i<0)i=source.indexOf('create function '+name+'(');assert(i>=0,name);return source.slice(i,source.indexOf('$$;',i)+3);};
await db.exec(extract(sql('20260910120000_department_management.sql'),'provision_private.work_service_version_guard'));
await db.exec('create trigger work_service_version_guard before update on work_services for each row execute function provision_private.work_service_version_guard()');
await db.exec(live.find(row=>row.name==='work_department_save').definition);
await db.exec(extract(sql('20260915081811_employee_work_profile.sql'),'public.work_employee_profile'));
const payload={name:'قسم جديد',slug:'fixture-new',category:'الفريق',description:'',icon:'building-2',active:true,client_visible:true,default_target_minutes:120,default_effort_points:2,sort_order:100,responsibilities:['تنفيذ الطلبات'],tasks:['تسليم المخرجات'],member_ids:[id(3),id(7)],lead_user_id:id(3)};
await as(2);await assert.rejects(()=>query('select work_department_save($1::jsonb)',[JSON.stringify(payload)]),/forbidden/);
await as(6);
const saved=(await query('select work_department_save($1::jsonb) result',[JSON.stringify(payload)]))[0].result;
const profile=async()=> (await query('select work_employee_profile($1) result',[id(3)]))[0].result;
assert((await profile()).services.includes(saved.id));assert((await profile()).services.includes(id(21)));
assert((await profile()).lead_services.includes(saved.id));assert((await profile()).lead_services.includes(id(21)));
await query('select work_department_save($1::jsonb)',[JSON.stringify({...payload,id:saved.id,version:saved.version,member_ids:[id(7)],lead_user_id:id(7)})]);
assert(!(await profile()).services.includes(saved.id));assert((await profile()).services.includes(id(21)));
await assert.rejects(()=>query('select work_department_save($1::jsonb)',[JSON.stringify({...payload,id:saved.id,version:saved.version})]),/department_version_conflict/);
// Metric samples retain department identity independently of current membership
await db.exec('alter table work_parts disable trigger all');
await query('update work_requests set test=false where id=$1',[id(10)]);
await query('update work_parts set performance_eligible=false');
for(let n=0;n<5;n++)await query(`insert into work_parts(id,request_id,service_id,assignee_id,scope,status,route_position,assigned_at,completed_at,effort_points,target_minutes,accountable_seconds,performance_eligible)
 values($1,$2,$3,$4,'مهمة قياس','approved',$5,now()-interval '1 hour',now(),2,60,7200,true)`,[id(700+n),id(10),id(20),id(2),700+n]);
const departmentReport=async()=>(await query("select work_department_performance(date_trunc('month',now() at time zone 'Asia/Riyadh')::date,(now() at time zone 'Asia/Riyadh')::date) value"))[0].value;
let metric=(await departmentReport()).departments.find(row=>row.id===id(20));
assert.equal(metric.completed_count,5);assert.equal(metric.speed_score,50);assert.equal(metric.productivity_score,100);assert.equal(metric.performance_score,68);
assert.equal((await departmentReport()).departments.find(row=>row.id===saved.id).performance_score,null);
let winners=(await query('select work_employee_of_month() result'))[0].result;
assert.equal(winners.people[0].id,id(2));assert.equal(winners.people[0].rank,1);
assert.equal(winners.period.start_date.slice(-2),'01');assert.equal(winners.people.length,1);
await query("insert into auth.users(id,raw_app_meta_data) values($1,'{\"role\":\"employee\"}')",[id(9)]);
await query('insert into work_staff(user_id) values($1)',[id(9)]);
for(const employee of [3,7,9])for(let n=0;n<5;n++)await query(`insert into work_parts(id,request_id,service_id,assignee_id,scope,status,route_position,assigned_at,completed_at,effort_points,target_minutes,accountable_seconds,performance_eligible)
 values($1,$2,$3,$4,'مهمة ترتيب','approved',$5,now()-interval '1 hour',now(),2,60,7200,true)`,[id(800+employee*10+n),id(10),id(21),id(employee),800+employee*10+n]);
winners=(await query('select work_employee_of_month() result'))[0].result;
assert.deepEqual(winners.people.map(person=>person.id),[id(2),id(3),id(7)],'top three only with deterministic tie handling');
assert.deepEqual(winners.people.map(person=>person.rank),[1,2,3]);
const previous=(await query("select work_employee_of_month((date_trunc('month',now() at time zone 'Asia/Riyadh')-interval '1 day')::date) result"))[0].result;
assert.equal(previous.people.length,0,'previous month does not include current month work');
await query('update work_requests set test=true where id=$1',[id(10)]);
assert.equal((await departmentReport()).departments.find(row=>row.id===id(20)).completed_count,0);
assert.equal((await query('select work_employee_of_month() result'))[0].result.people.length,0);
await db.close();
console.log('PASS department membership sync multiple memberships stale saves output distribution and standalone departmental and calendar employee scores');
