// Isolated PostgreSQL Actual migration and routing RPCs No live writes
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {PGlite} from '../../.tools/sql-check/node_modules/@electric-sql/pglite/dist/index.js';
const source=readFileSync('tests/sql/department-cards.mjs','utf8');
const start=source.indexOf('const fixture='),end=source.indexOf('await as(2);');
const membershipStart=source.indexOf('// Department membership'),membershipEnd=source.indexOf('const payload=');
assert(start>=0&&end>start&&membershipEnd>membershipStart);
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const {db,extract}=await new AsyncFunction('PGlite','readFileSync','assert',source.slice(start,end)+source.slice(membershipStart,membershipEnd)+'return {db,extract};')(PGlite,readFileSync,assert);
const sql=file=>readFileSync('supabase/migrations/'+file,'utf8');
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const query=async(q,args=[])=>(await db.query(q,args)).rows;
const as=async n=>query("select set_config('test.uid',$1,false)",[n?id(n):'']);
for(const row of JSON.parse(readFileSync('.tools/department-team-permission-functions.json','utf8')))await db.exec(row.definition);
await db.exec(extract(sql('20260913183556_admin_catalog_permissions.sql'),'public.work_catalog_service_save'));
await db.exec("create unique index work_memberships_one_lead_per_department on work_memberships(service_id) where member_role='lead'; create unique index fixture_service_slug on work_services(slug)");
await db.exec(sql('20260920111601_department_team_multiple_leads.sql'));
const save=async p=>(await query('select work_department_team_save($1::jsonb) result',[JSON.stringify(p)]))[0].result;
const payload={id:id(21),version:1,member_ids:[id(3),id(7)],lead_user_ids:[id(3),id(7)]};
for(const user of [null,1,2,3]){await as(user);await assert.rejects(()=>save(payload),/forbidden/);}
await as(6);
const before=(await query('select to_jsonb(s)-\'version\'-\'updated_at\' value from work_services s where id=$1',[id(21)]))[0].value;
let saved=await save(payload);
assert.equal(saved.version,2);
assert.deepEqual((await query('select to_jsonb(s)-\'version\'-\'updated_at\' value from work_services s where id=$1',[id(21)]))[0].value,before,'membership save preserves operational metadata');
assert.equal((await query("select count(*)::int count from work_memberships where service_id=$1 and member_role='lead'",[id(21)]))[0].count,2);
for(const user of [3,7]){
 const profile=(await query('select work_employee_profile($1) value',[id(user)]))[0].value;
 assert(profile.services.includes(id(21)));assert(profile.lead_services.includes(id(21)));
}
assert((await query('select service_id from work_memberships where user_id=$1',[id(7)])).some(row=>row.service_id===id(22)),'other departments preserved');
await assert.rejects(()=>save(payload),/department_version_conflict/);
await assert.rejects(()=>save({...payload,version:2,lead_user_ids:[]}),/invalid_department/);
await assert.rejects(()=>save({...payload,version:2,lead_user_ids:[id(2)]}),/lead_must_be_member/);
await assert.rejects(()=>save({...payload,version:2,member_ids:[id(1)],lead_user_ids:[id(1)]}),/invalid_department_member/);
await assert.rejects(()=>save({...payload,version:2,member_ids:[id(3),id(3)]}),/duplicate_department_item/);
await assert.rejects(()=>save({...payload,version:2,active:false}),/invalid_department/);
const legacy={...payload,version:2,name:'قسم الاختبار',slug:'fixture-old',category:'الفريق',description:'',icon:'building-2',active:true,client_visible:true,default_target_minutes:120,default_effort_points:2,sort_order:100,responsibilities:['تنفيذ الطلبات'],tasks:['تسليم المخرجات'],lead_user_id:id(3)};
delete legacy.lead_user_ids;
await assert.rejects(()=>query('select work_department_save($1::jsonb)',[JSON.stringify(legacy)]),/department_team_editor_required/);
assert.equal((await query('select version from work_services where id=$1',[id(21)]))[0].version,2,'failed saves are atomic');
// Several leads still produce one child assignment The other lead may distribute it
await as(2);
const requestVersion=async()=>(await query('select version from work_requests where id=$1',[id(10)]))[0].version;
await query("select work_output_action('request_outputs',$1::jsonb)",[JSON.stringify({request_id:id(10),part_id:id(30),version:await requestVersion(),submission_key:id(500),outputs:[{service_id:id(21),reason:'مخرجات مطلوبة'}]})]);
const children=await query('select * from work_parts where output_parent_id=$1',[id(30)]);
assert.equal(children.length,1);assert.equal(children[0].assignee_id,id(3));assert.equal(children[0].output_distribution_pending,true);
await as(7);
await query("select work_action('delegate',$1::jsonb)",[JSON.stringify({request_id:id(10),part_id:children[0].id,version:await requestVersion(),assignee_id:id(7)})]);
assert.equal((await query('select assignee_id from work_parts where id=$1',[children[0].id]))[0].assignee_id,id(7));
await as(6);
saved=await save({...payload,version:2,lead_user_ids:[id(7)]});
assert.equal((await query('select member_role from work_memberships where user_id=$1 and service_id=$2',[id(3),id(21)]))[0].member_role,'member','unchecking lead keeps membership');
saved=await save({...payload,version:saved.version,member_ids:[id(7)],lead_user_ids:[id(7)]});
assert.equal((await query('select * from work_memberships where user_id=$1 and service_id=$2',[id(3),id(21)])).length,0);
const fresh={id:null,version:null,name:'قسم جديد بفريق فقط',slug:'department-'+id(900),member_ids:[id(3),id(7)],lead_user_ids:[id(3),id(7)]};
const created=await save(fresh);
assert.equal((await query('select count(*)::int count from work_department_tasks where service_id=$1',[created.id]))[0].count,0);
await assert.rejects(()=>save(fresh),/department_conflict/);
await query('update work_services set active=false where id=$1',[created.id]);
const activeVersion=(await query('select version from work_services where id=$1',[created.id]))[0].version;
const catalog={id:created.id,version:activeVersion,name:fresh.name,slug:fresh.slug,category:'أقسام برو فيجن',description:'',icon:'building-2',active:true,client_visible:true,default_target_minutes:4320,default_effort_points:5,sort_order:100};
await query('select work_catalog_service_save($1::jsonb)',[JSON.stringify(catalog)]);
assert.equal((await query('select active from work_services where id=$1',[created.id]))[0].active,true);
assert.equal((await query("select has_function_privilege('anon','public.work_department_team_save(jsonb)','execute') allowed"))[0].allowed,false);
assert.equal((await query("select has_function_privilege('authenticated','public.work_department_team_save(jsonb)','execute') allowed"))[0].allowed,true);
assert((await query("select details from provision_private.audit where action='work_department_team_update'")).some(row=>row.details.lead_user_ids.length===2));
await db.close();
console.log('PASS multiple leads membership sync atomic guards settings preservation single output distribution catalog activation and grants');
